# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.0
      - name: Cache HaxeLib
        uses: actions/cache@v2
        with:
          path: |
            C:/haxelib
          key: Haxelib
      - name: Cache FNFBRBIN
        uses: actions/cache@v2
        with:
          path: |
            C:/fnfbrbin
          key: Bin
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install linc_luajit
          haxelib install newgrounds
          haxelib git crashdumper http://github.com/larsiusprime/crashdumper
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.2.5-${{ github.run_id}}" -Dghaction
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: C:/fnfbrbin/windows/bin      
      - name: Publish without changed assets as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild-Minimal
          path: |
                C:/fnfbrbin/windows/bin/FNF Battle Royale.exe
                C:/fnfbrbin/windows/bin/manifest
                C:/fnfbrbin/windows/bin/mods
                C:/fnfbrbin/windows/bin/assets/shared/images/NOTE_assets.xml
                C:/fnfbrbin/windows/bin/assets/shared/images/NOTE_assets.png
                C:/fnfbrbin/windows/bin/assets/shared/images/NOTE_assets_bad.xml
                C:/fnfbrbin/windows/bin/assets/shared/images/NOTE_assets_bad.png
                C:/fnfbrbin/windows/bin/assets/shared/images/noteSplashes.xml
                C:/fnfbrbin/windows/bin/assets/shared/images/noteSplashes.png
                C:/fnfbrbin/windows/bin/assets/preload/images/num1.png
                C:/fnfbrbin/windows/bin/assets/music
                C:/fnfbrbin/windows/bin/assets/images/onlinemod
                C:/fnfbrbin/windows/bin/assets/data/introText.txt
                C:/fnfbrbin/windows/bin/assets/data/characterMetadata.json
                C:/fnfbrbin/windows/bin/assets/sounds/Hit_Sound.ogg

